# apps/api/models/lead_model.py
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, String, Integer, Float, DateTime

Base = declarative_base()

class LeadCompletoDetalhado(Base):
    __tablename__ = "mv_lead_completo_detalhado"   # ou 'vw_lead_completo_detalhado'
    __table_args__ = {"schema": "intel_lead"}       # schema

    # Colunas (iguais às da view)
    uc_id = Column(String, primary_key=True)
    import_id = Column(String, nullable=True)
    cod_id = Column(String, nullable=True)
    distribuidora_id = Column(Integer, nullable=True)
    origem = Column(String, nullable=True)
    ano = Column(Integer, nullable=True)
    status = Column(String, nullable=True)
    data_conexao = Column(DateTime, nullable=True)
    grupo_tensao = Column(String, nullable=True)
    modalidade = Column(String, nullable=True)
    tipo_sistema = Column(String, nullable=True)
    situacao = Column(String, nullable=True)
    classe = Column(String, nullable=True)
    cnae = Column(String, nullable=True)
    municipio_id = Column(Integer, nullable=True)
    municipio = Column(String, nullable=True)
    estado = Column(String, nullable=True)
    bairro = Column(String, nullable=True)
    cep = Column(String, nullable=True)
    pac = Column(Float, nullable=True)
    pn_con = Column(String, nullable=True)
    descricao = Column(String, nullable=True)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    distribuidora_nome = Column(String, nullable=True)
    cnae_descricao = Column(String, nullable=True)
    segmento_desc = Column(String, nullable=True)
    cnpj = Column(String, nullable=True)
    nome_fantasia = Column(String, nullable=True)
    razao_social = Column(String, nullable=True)
    telefone = Column(String, nullable=True)
    email = Column(String, nullable=True)
    site = Column(String, nullable=True)
    receita_situacao = Column(String, nullable=True)
    receita_abertura = Column(String, nullable=True)
    receita_natureza = Column(String, nullable=True)
    receita_porte = Column(String, nullable=True)
    receita_capital_social = Column(String, nullable=True)
    receita_atividade_principal = Column(String, nullable=True)
    receita_municipio = Column(String, nullable=True)
    receita_uf = Column(String, nullable=True)
    enriched_at = Column(String, nullable=True)
    media_dic = Column(Float, nullable=True)
    soma_horas_sem_rede = Column(Float, nullable=True)
    media_energia_total = Column(Float, nullable=True)
    media_demanda_ponta = Column(Float, nullable=True)
    media_demanda_fora = Column(Float, nullable=True)

