FROM python:3.11-slim

WORKDIR /app

# Instala dependências do sistema
RUN apt-get update && apt-get install -y \
    g++ git curl unzip libgdal-dev gdal-bin python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia todo o projeto para o container
COPY . .

# Instala as dependências Python
RUN pip install --upgrade pip && pip install -r requirements.txt

# Comando padrão: roda o orquestrador automaticamente
CMD ["python", "packages/orquestrator/orquestrador_job.py"]
